version: '3'

services:
  fastapi:
    image: ujstor/fastqpi
    ports:
      - '8010:8010'
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}, ${DATABASE_NAME}_test
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/postgres/fastapi